### ISSUE TITLE
Runtime Error 6 Overflow

### ISSUE THREAD

**Issue by ghost** [ABN-SFLookupTechnicalSupport/ABNLookupSampleCode#4]
As per subject, I am encountering issue using the xls ABNLookup whenever I place more than 12k ABN records to search.
Kindly help

**Comment by ABN-SFLookupTechnicalSupport** [comment]
Hi ghost,

We recently deployed a fix for a similar issue. Please ensure you are using the latest version of the the ABNLookup tools which you can download here:
https://abr.business.gov.au/Tools/AbnLookup

From our internal testing we were able to query over 66k ABNs before we hit the limitation of Excel having over 66k hyperlinks in one spreadsheet.
https://support.office.com/en-ie/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3#ID0EBABAAA=Newer_versions
