### ISSUE TITLE
Having trouble testing the endpoint

### ISSUE THREAD

**Issue by pangkoi101** [ABN-SFLookupTechnicalSupport/ABNLookupSampleCode#5]
So I have tried this:

http://abr.business.gov.au/abrxmlsearch/ABRXMLSearch.asmx/SearchByABNv201408?searchstring=asd&includeHistoricalDetails=Y&authenticationGuid=MyGuid

and i got this error:

<exceptionDescription>Search text is not a valid ABN or ACN</exceptionDescription>

if i remove searchString then 

i got Missing parameter: searchString.
Really confused...

**Comment by Nightsoil** [comment]
Hey pangkoi101, try using a valid ABN as the parameter when using the SearchByABN webservice.
for eg. 51824753556

If you would prefer to search using a string, try using the SeachByName webservice. See example here:
https://abr.business.gov.au/abrxmlsearch/Forms/ABRSearchByNameAdvancedSimpleProtocol2017.aspx

for additional help with the webservice parameters check out this page:
https://abr.business.gov.au/Documentation/WebServiceMethods
