### ISSUE TITLE
the SDK get different info from web portal

### ISSUE THREAD

**Issue by Hanwen196** [ABN-SFLookupTechnicalSupport/ABNLookupSampleCode#6]
Hi, I am trying to use JAVA SDK to get relevant information with an ABN.

I am having trouble when checking against sole trader. In your api, I cannot find something like getEntityName(), but only getOrganizationName() .

When I am using web portal to check relevant info, I can find entity name on an individual person.

Do you have some kind of API to get some "name" no matter what kind ABN i am giving to you?

Many thanks.

**Comment by ABN-SFLookupTechnicalSupport** [comment]
Hi Hanwen196,

Pls have a look the sample code especially AbnSearchResult.java.
This is the class for the AbnSearchResult where it defines this method getOrganisationName()
The method retrieves the organisationName from the response called searchResultsPayload.

For sole trader, legalName is the node to inspect.

Pls check the sample searchResultsPayload  on this AbrXmlSearch page https://abr.business.gov.au/abrxmlsearch/Forms/SearchByABNv201408.aspx

![image](https://user-images.githubusercontent.com/43945280/72582447-e0c14080-3936-11ea-8069-d4f7c6d0a6f5.png)

Hope this help. Let me know if you need more information.

Thanks
Teddy
